actor_model:
  # experiment/model/actor_model.yaml
  _target_: trainers.models.gnn_policy_model.MyModelConfig
  # ─── GNN settings ────────────────────────────────────────────────────────────
  topology: from_pos
  edge_radius: ${..model_shared.comms_radius}   # ← relative path, one level up
  self_loops: false
  gnn_class: torch_geometric.nn.conv.GATv2Conv
  gnn_kwargs:
    add_self_loops: true
    residual: true

  # ─── Feature keys & sizes ────────────────────────────────────────────────────
  position_key: pos         # 2-D agent positions
  pos_features: 2
  velocity_key: vel
  vel_features: 2
  sentence_key: sentence_embedding
  exclude_pos_from_node_features: false

  # ─── MLP head ────────────────────────────────────────────────────────────────
  num_cells: [256, 256]
  layer_class: torch.nn.Linear
  activation_class: torch.nn.ReLU

  # ─── Toggles ─────────────────────────────────────────────────────────────────
  use_gnn: ${..model_shared.use_gnn}
  use_encoder: ${..model_shared.use_encoder}

  gnn_emb_dim: ${..model_shared.gnn_emb_dim}

  encoder_dim: ${..model_shared.encoder_dim}
  encoder_num_cells: ${..model_shared.encoder_num_cells}
