critic_model:
  # experiment/model/critic_model.yaml
  _target_: trainers.models.gnn_policy_model.MyModelConfig

  # ─── Feature keys ────────────────────────────────────────────────────────────
  position_key: pos         # 2-D agent positions
  pos_features: 2
  velocity_key: vel
  vel_features: 2
  sentence_key: sentence_embedding
  exclude_pos_from_node_features: false

  # ─── MLP head ────────────────────────────────────────────────────────────────
  num_cells: [512, 256]        # bigger first layer than actor
  layer_class: torch.nn.Linear
  activation_class: torch.nn.ReLU

  # ─── Toggles ─────────────────────────────────────────────────────────────────
  use_gnn: false
  use_encoder: ${..model_shared.use_encoder}

  gnn_emb_dim: ${..model_shared.gnn_emb_dim}
  
  encoder_dim: ${..model_shared.encoder_dim}
  encoder_num_cells: ${..model_shared.encoder_num_cells}
