critic_model:
  # experiment/model/critic_model.yaml
  _target_: trainers.models.benchmarl_model_wrappers.MyModelConfig

  # (No GNN for the critic -- we drop the topology/edge-radius fields)

  # ─── Feature keys ────────────────────────────────────────────────────────────
  position_key: pos         # 2-D agent positions
  pos_features: 2
  velocity_key: vel
  vel_features: 2
  sentence_key: sentence_embedding
  grid_key: grid_obs
  target_key: target_obs
  obstacle_key: obstacle_obs
  exclude_pos_from_node_features: false

  # ─── MLP head ────────────────────────────────────────────────────────────────
  num_cells: [512, 256]        # bigger first layer than actor
  layer_class: torch.nn.Linear
  activation_class: torch.nn.ReLU

  # ─── Toggles ─────────────────────────────────────────────────────────────────
  use_gnn: false
  use_encoder: ${..model_shared.use_encoder}
  use_conv_2d: ${..model_shared.use_conv_2d}

  cnn_emb_dim : ${..model_shared.cnn_emb_dim}
  cnn_filters: ${..model_shared.cnn_filters}
  cnn_spatial: ${..model_shared.cnn_spatial}

  gnn_emb_dim: ${..model_shared.gnn_emb_dim}
  
  encoder_dim: ${..model_shared.encoder_dim}
  encoder_num_cells: ${..model_shared.encoder_num_cells}
